import * as plantumlEncoder from "plantuml-encoder"
import * as http from "http"
import * as fs from "fs"
import { Logger } from "./logger"

const logger = new Logger("plantuml")

function parseListToSequence(srcListString: string[], start: number, end: number, sequenceDiagram: string[] = [], participants: string[] = [], indent: number = 0, debug: boolean = false): void {
    // 预处理
    if (indent === 0) {
        const fileNamesDict: Record<string, string> = {}; // 新增：文件名映射字典

        sequenceDiagram.push("@startuml");

        sequenceDiagram.push("");
        sequenceDiagram.push("title Sequence Diagram");
        sequenceDiagram.push("");
        sequenceDiagram.push("' Auto generated by MDPlant");
        sequenceDiagram.push("' https://github.com/FolderLevel/MDPlant");
        sequenceDiagram.push("");

        // 检测 if/else 并转换为 PlantUML 的 alt/else/end 结构
        const ifIndexs = [];
        let lineIndex = 0;
        for (lineIndex = 0; lineIndex < srcListString.length; lineIndex++) {
            const line = srcListString[lineIndex];
            const matchObj = line.match(/\s*\* (if)\s*\((.*)\)/);
            if (matchObj) {
                ifIndexs.push(lineIndex);
            }
        }
        ifIndexs.reverse();
        for (const ifIndex of ifIndexs) {
            let spaceIndent = "";
            for (lineIndex = ifIndex; lineIndex < srcListString.length; lineIndex++) {
                const line = srcListString[lineIndex];
                const matchObj = line.match(/(\s*)\* if\s*\((.*)\)/);
                if (matchObj) {
                    srcListString[lineIndex] = matchObj[1] + "* alt " + matchObj[2];
                    spaceIndent = matchObj[1];
                    continue;
                }
                const elseMatchObj = line.match(/(\s*)\* (else|elif)\s*\((.*)\)/);
                if (elseMatchObj) {
                    srcListString[lineIndex] = elseMatchObj[1] + "* else " + elseMatchObj[3];
                    continue;
                }
                if (line.split("* ")[0].length <= spaceIndent.length) {
                    srcListString.splice(lineIndex, 0, spaceIndent + "* end");
                    break;
                }
            }

            lineIndex--;

            if ((lineIndex === (srcListString.length - 1)) && (srcListString[lineIndex].split("* ")[0] !== spaceIndent)) {
                srcListString.push(spaceIndent + "* end");
            }
        }

        // 其他行内修改，譬如文件路径、函数、while/for、参数
        for (let lineIndex = 0; lineIndex < srcListString.length; lineIndex++) {
            let line = srcListString[lineIndex];
            if (line.includes("\\")) {
                // line = line.replaceAll("\\", "/");
                line = line.replace(/\\/g, '/');
            }

            // path
            if (line.includes("/") || line.includes(".")) {
                const matchObj = line.match(/\s*\* ((.*\/)*(.*\.[c|cpp|java]))/);
                if (matchObj) {
                    srcListString[lineIndex] = line.replace(matchObj[1], matchObj[3]);
                    fileNamesDict[matchObj[3]] = matchObj[1]; // 新增：记录文件名与路径的映射
                    continue;
                }
            }

            // skip function
            let matchObj = line.match(/\s*\* ((\S+ )\S+)\(.*\)/);
            if (matchObj) {
                if (lineIndex !== 1) {
                    srcListString[lineIndex] = "";
                    continue;
                } else {
                    srcListString[lineIndex] = line.replace(matchObj[2], "");
                    line = srcListString[lineIndex];
                }
            }

            // 新增逻辑：检测循环结构
            matchObj = line.match(/\s*\* (for|while)\s*\((.*)\)/);
            if (matchObj) {
                srcListString[lineIndex] = line.split("* ")[0] + "* loop " + matchObj[2];
                continue;
            }

            // skip parameter
            const paramMatchObj = line.match(/\s*\* .+\((.*)\)/);
            if (paramMatchObj) {
                srcListString[lineIndex] = line.replace(paramMatchObj[1], "");
            }
        }

        // remove file name
        for (let lineIndex = srcListString.length - 1; lineIndex >= 0; lineIndex--) {
            const line = srcListString[lineIndex];
            const matchObj = line.match(/\s*\* (.*\.[c|cpp|java])$/);
            if (matchObj) {
                if (lineIndex === 0) {
                    srcListString[lineIndex] = "";
                    srcListString[lineIndex + 1] = srcListString[lineIndex + 1].replace("  * ", "* " + matchObj[1] + " @ ");
                } else {
                    srcListString[lineIndex] = "";
                    srcListString[lineIndex - 1] = srcListString[lineIndex - 1].replace(" * ", " * " + matchObj[1] + " @ ");
                }
            }
        }

        // remove empty line
        for (let lineIndex = srcListString.length - 1; lineIndex >= 0; lineIndex--) {
            if (srcListString[lineIndex].trim().length === 0) {
                srcListString.splice(lineIndex, 1);
            }
        }

        // reduce indent when indent is 4 for remove empty line
        const lineCount = srcListString.length;
        let preIndent = srcListString[lineCount - 1].length - srcListString[lineCount - 1].trimStart().length;
        for (let lineIndex = lineCount - 1; lineIndex >= 0; lineIndex--) {
            const currentLine = srcListString[lineIndex];
            const currentIndent = currentLine.length - currentLine.trimStart().length;

            if (preIndent - currentIndent > 2) {
                const fixIndent = srcListString[lineIndex + 1].length - srcListString[lineIndex + 1].trimStart().length - currentIndent - 2;

                for (let fixIndex = (lineIndex + 1); fixIndex < srcListString.length; fixIndex++) {
                    const currentFixIndent = srcListString[fixIndex].length - srcListString[fixIndex].trimStart().length;
                    if (currentFixIndent > (currentIndent + 2)) {
                        srcListString[fixIndex] = srcListString[fixIndex].slice(fixIndent);
                    } else {
                        break;
                    }
                }
            }

            preIndent = currentIndent;
        }

        // 可能因为处理if/else添加了行，调整end
        end = srcListString.length;

        // 新增：添加文件名与路径的映射注释
        sequenceDiagram.push("note across");
        for (const fileName in fileNamesDict) {
            sequenceDiagram.push("* " + fileName + ": " + fileNamesDict[fileName]);
        }
        sequenceDiagram.push("end note");
        sequenceDiagram.push("");

        // dump出预处理，便于观察预处理是否存在问题
        console.log(srcListString);
    }

    if (end > srcListString.length) {
        end = srcListString.length;
    }

    if (debug) {
        console.log("-------------------");
        console.log(("  ".repeat(indent)) + start + "," + end);
    }

    let lineIndex = 0;
    const indentList = [start];
    let currentIndent = srcListString[start].length - srcListString[start].trimStart().length;
    if (start + 1 < end) {
        for (lineIndex = start + 1; lineIndex < end; lineIndex++) {
            const nextIndent = srcListString[lineIndex].length - srcListString[lineIndex].trimStart().length;
            if (nextIndent === currentIndent) {
                indentList.push(lineIndex);
            } else if (nextIndent > currentIndent) {
                continue;
            } else {
                break;
            }
        }

        if (lineIndex === end) {
            indentList.push(lineIndex);
        }
    } else {
        indentList.push(end);
    }

    if (debug) {
        console.log(indentList);
        console.log(participants);
    }

    if (indentList.length === 2 && indentList[1] - indentList[0] === 1) {
        const matchObj = srcListString[indentList[0]].match(/(\s*)\* ((\S+\.[c|cpp|java]) @ )/);
        if (matchObj) {
            currentIndent = matchObj[1].length;
            if (indent === 0) {
                participants.push("User");
            } else if (participants.length > 1) {
                participants.shift();
            }

            participants.push(matchObj[3]);
        } else {
            if (participants.length > 1) {
                participants.shift();
            }
        }

        if (participants.length === 1) {
            srcListString[indentList[0]] = srcListString[indentList[0]].replace(" * ", " * " + participants[0] + " -> " + participants[0] + " ++: ");

            // 区分出行内注释
            const commentStr = srcListString[indentList[0]].split("//")[1]?.trim() || "";
            if (commentStr) {
                srcListString[indentList[0]] = srcListString[indentList[0]].split("//")[0].replace(/\s*$/g, "");
            }

            sequenceDiagram.push(srcListString[indentList[0]]);
            // 添加注释
            if (commentStr) {
                sequenceDiagram.push("  ".repeat(indent + 1) + "note right: " + commentStr);
            }
            sequenceDiagram.push("  ".repeat(indent) + "* deactivate " + participants[0]);
        } else {
            if (matchObj) {
                srcListString[indentList[0]] = srcListString[indentList[0]].replace(matchObj[2], participants[0] + " -> " + participants[1] + " ++: ");

                // 区分出行内注释
                const commentStr = srcListString[indentList[0]].split("//")[1]?.trim() || "";
                if (commentStr) {
                    srcListString[indentList[0]] = srcListString[indentList[0]].split("//")[0].replace(/\s*$/g, "");
                }

                sequenceDiagram.push(srcListString[indentList[0]]);
                // 添加注释
                if (commentStr) {
                    sequenceDiagram.push("  ".repeat(indent + 1) + "note right: " + commentStr);
                }
                sequenceDiagram.push("  ".repeat(indent) + "* " + participants[0] + " <-- " + participants[1] + " --");
                sequenceDiagram.push("  ".repeat(indent) + "* deactivate " + participants[1]);
            }
        }

        if (debug) {
            console.log(srcListString[indentList[0]]);
        }

        return;
    } else {
        const participantsBak = [...participants];
        let forStatus = false;

        for (let startIndex = 0; startIndex < indentList.length - 1; startIndex++) {
            participants = [...participantsBak];
            let listStringStriped = srcListString[indentList[startIndex]].trim()

            if (indentList.length > 2) {
                if (!(listStringStriped.startsWith("* end"))) {
                    sequenceDiagram.push("");
                }
            }

            if (indentList[startIndex + 1] - indentList[startIndex] > 1) {
                const matchObj = srcListString[indentList[startIndex]].match(/(\s*)\* ((\S+\.[c|cpp|java]) @ )/);
                if (matchObj) {
                    currentIndent = matchObj[1].length;
                    if (indent === 0) {
                        participants.push("User");
                    } else if (participants.length > 1) {
                        participants.shift();
                    }

                    participants.push(matchObj[3]);
                } else {
                    if (participants.length > 1) {
                        participants.shift();
                    }
                }

                if (debug) {
                    console.log(participants);
                }

                // if/else在预处理部分已经处理了
                if (!(listStringStriped.startsWith("* alt ") || listStringStriped.startsWith("* else ") || listStringStriped.startsWith("* end"))) {
                    // 检测循环结构
                    if (listStringStriped.startsWith("* loop ")) {
                        forStatus = true;
                    } else {
                        if (participants.length === 1) {
                            srcListString[indentList[startIndex]] = srcListString[indentList[startIndex]].replace(" * ", " * " + participants[0] + " -> " + participants[0] + " ++: ");
                        } else {
                            if (matchObj) {
                                srcListString[indentList[startIndex]] = srcListString[indentList[startIndex]].replace(matchObj[2], participants[0] + " -> " + participants[1] + " ++: ");
                            }
                        }
                    }
                }

                if (debug) {
                    console.log(srcListString[indentList[startIndex]]);
                }

                // 区分出行内注释
                const commentStr = srcListString[indentList[startIndex]].split("//")[1]?.trim() || "";
                if (commentStr) {
                    srcListString[indentList[startIndex]] = srcListString[indentList[startIndex]].split("//")[0].replace(/\s*$/g, "");
                }

                sequenceDiagram.push(srcListString[indentList[startIndex]]);
                // 添加注释
                if (commentStr) {
                    sequenceDiagram.push("  ".repeat(indent + 1) + "note right: " + commentStr);
                }

                const participantsSub = [...participants];
                parseListToSequence(srcListString, indentList[startIndex] + 1, indentList[startIndex + 1], sequenceDiagram, participants, indent + 1, debug);
                participants.length = 0;
                participants.push(...participantsSub);

                // if/else在预处理部分已经处理了
                if (!(listStringStriped.startsWith("* alt ") || listStringStriped.startsWith("* else ") || listStringStriped.startsWith("* end"))) {
                    if (forStatus) {
                        sequenceDiagram.push("  ".repeat(indent) + "end");
                    } else {
                        if (participants.length === 1) {
                            sequenceDiagram.push("  ".repeat(indent) + "* deactivate " + participants[0]);
                        } else {
                            sequenceDiagram.push("  ".repeat(indent) + "* " + participants[0] + " <-- " + participants[1] + " --");
                            sequenceDiagram.push("  ".repeat(indent) + "* deactivate " + participants[1]);
                        }
                    }
                }
            } else {
                const matchObj = srcListString[indentList[startIndex]].match(/(\s*)\* ((\S+\.[c|cpp|java]) @ )/);
                if (matchObj) {
                    currentIndent = matchObj[1].length;
                    if (indent === 0) {
                        participants.push("User");
                    } else if (participants.length > 1) {
                        participants.shift();
                    }
                    participants.push(matchObj[3]);
                    srcListString[indentList[startIndex]] = srcListString[indentList[startIndex]].replace(matchObj[2], "");
                } else {
                    if (participants.length > 1) {
                        participants.shift();
                    }
                }

                // if/else在预处理部分已经处理了
                if (!(listStringStriped.startsWith("* alt ") || listStringStriped.startsWith("* else ") || listStringStriped.startsWith("* end"))) {
                    if (participants.length === 1) {
                        srcListString[indentList[startIndex]] = srcListString[indentList[startIndex]].replace(" * ", " * " + participants[0] + " -> " + participants[0] + " ++: ");
                    } else {
                        if (matchObj) {
                            srcListString[indentList[startIndex]] = srcListString[indentList[startIndex]].replace(matchObj[2], participants[0] + " -> " + participants[1] + " ++: ");
                        }
                    }

                    // 区分出行内注释
                    const commentStr = srcListString[indentList[startIndex]].split("//")[1]?.trim() || "";
                    if (commentStr) {
                        srcListString[indentList[startIndex]] = srcListString[indentList[startIndex]].split("//")[0].replace(/\s*$/g, "");
                    }

                    if (participants.length === 1) {
                        sequenceDiagram.push(srcListString[indentList[startIndex]]);
                        // 添加注释
                        if (commentStr) {
                            sequenceDiagram.push("  ".repeat(indent + 1) + "note right: " + commentStr);
                        }
                        sequenceDiagram.push("  ".repeat(indent) + "* deactivate " + participants[0]);
                    } else {
                        sequenceDiagram.push(srcListString[indentList[startIndex]]);
                        // 添加注释
                        if (commentStr) {
                            sequenceDiagram.push("  ".repeat(indent + 1) + "note right: " + commentStr);
                        }
                        sequenceDiagram.push("  ".repeat(indent) + "* " + participants[0] + " <-- " + participants[1] + " --");
                        sequenceDiagram.push("  ".repeat(indent) + "* deactivate " + participants[1]);
                    }
                } else {
                    sequenceDiagram.push(srcListString[indentList[startIndex]])
                }

                if (debug) {
                    console.log(srcListString[indentList[startIndex]]);
                }
            }

            if ((indentList.length > 2) && (startIndex == (indentList.length - 2))) {
                sequenceDiagram.push("")
            }
        }
    }

    if (indent === 0) {
        for (let lineIndex = start; lineIndex < end; lineIndex++) {
            srcListString[lineIndex] = srcListString[lineIndex].replace("* ", "");
        }

        sequenceDiagram.push("");
        sequenceDiagram.push("@enduml");
        for (let lineIndex = 0; lineIndex < sequenceDiagram.length; lineIndex++) {
            sequenceDiagram[lineIndex] = sequenceDiagram[lineIndex].replace("* ", "");
        }
    }
}

/**
 * 
 * @param {string[]} contentArray 
 * @param {number} skipLevel 
 * @returns 
 */
function convert2SequenceDiagram(contentArray: string[], skipLevel: number): { status: boolean; content: string } {
    const sequenceDiagram: string[] = [];
    parseListToSequence(contentArray, 0, contentArray.length, sequenceDiagram, [], 0, false);

    return {"status": true, "content": sequenceDiagram.join("\n")}
}

/**
 * 
 * @param {string} umlString 
 * @param {string} plantumlServer 
 * @param {string} suffix 
 * @param {string} outputPath 
 * @param {(status: boolean) => void} cb 
 */
function getHTTPPlantumlImage(umlString: string, plantumlServer: string, suffix: string, outputPath: string, cb: (status: boolean) => void): void {
    let umlEncoded = plantumlEncoder.encode(umlString)

    function callback(err: unknown, cb: (status: boolean) => void, status: boolean): void {
        if (!status)
            logger.debug(err)

        if (cb != undefined)
            cb(status)
    }

    http.get(plantumlServer + '/' + suffix +  '/' + umlEncoded, (res) =>{
        let datas: Buffer[] = []
        let size = 0

        res.on("data", (data) => {
            datas.push(data)
            size += data.length
        })

        res.on("end", () => {
            try {
                fs.createWriteStream(outputPath).write(Buffer.concat(datas, size))
                callback("", cb, true)
            } catch(err) {
                callback(err, cb, false)
            }
        })

        res.on("error", (err) => {
            callback(err, cb, false)
        })
    }).on("error", (err) => {
        callback(err, cb, false)
    })
}

/**
 * 
 * @param {string[]} textBlock 
 * @param {string} rootPath 
 * @param {number} cursorOffset 
 * @returns 
 */
function isPlantuml(textBlock: string[], rootPath: string, cursorOffset: number): { status: boolean; content: string } {
    let found = false
    let content = ""
    let matchValue: RegExpExecArray | null
    let plantumlRE = new RegExp("\\s*(plantuml[\\s:]*([\\w\\/]*\\.(puml|plantuml|iuml|pu)?))", "g")

    logger.debug("enter isPlantuml")

    let startLine = 0
    for (let i = 0; i < textBlock.length; i++) {
        if (textBlock[i].trim().length != 0) {
            startLine = i
            break
        }
    }

    if (textBlock[0].trim().startsWith("```plantuml")) {
        logger.debug("plantuml block found")
        found = true
    } else if ((matchValue = plantumlRE.exec(textBlock[cursorOffset].trim()))){
        logger.debug("plantuml cmd found")
        found = true
        content = matchValue[1]
    } else if ((matchValue = plantumlRE.exec(textBlock[startLine].trim()))) {
        logger.debug("plantuml found")
        found = true
        content = matchValue[1]
    }

    return {"status": found, "content": content}
}

export {
    convert2SequenceDiagram,
    getHTTPPlantumlImage,
    isPlantuml,
}
